modLoader="javafml" #mandatory
#UPDATE
loaderVersion="[47,)"
license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

#updateJSONURL="http://myurl.me/"
#issueTrackerURL="http://my.issue.tracker/"

displayURL="https://wolforcept.github.io"
logoFile="logo.png"

credits="${mod_authors}"
authors="${mod_authors}"

# The description text for the mod (multi line!) (#mandatory)
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"